version: "3"
services:
  opentrecken_docs:
    image: ghcr.io/opentrecken/docs:latest
    build:
      context: .
      dockerfile: Dockerfile
    # ports are optional, only needed when running stand alone
    ports:
      - 4209:80